### ISSUE TITLE
HTML Wysiwyg modify code

### ISSUE THREAD

**Issue by KillWil** [COCOPi/cockpit#295]
Hello,
The HTML Wysiwyg entry type modify content when saving in the backoffice.

**Example code :**
```
<ul class="list icons list-unstyled">
<li><i class="fa fa-check"></i> Design</li>
```
**Result after saving :**
```
<ul class="list icons list-unstyled">
<li>Design</li>
```

**Comment by florianletsch** [comment]
Thanks for reporting.

Well this'll need some looking into, but I'm pretty sure this really is more related to the used wysiwyg editor TinyMCE. Looks like it removed empty elements. Maybe there's a setting we can just change to keep empty elements?

In general though, I'd always recommend using the code editor and not wysiwyg when working with HTML.

I think Cockpit didn't have any wysiwyg for a long time because of this reason. Artur then added it because of the need of a few people. Still, you can't expect those tools to keep your markup intact as they will always interfere with it. Better live without it. :)

**Comment by KillWil** [comment]
I agree but sometimes its necessary for end users to have an html editor...
I look forward to check if there is an option in tinyMCE to disable such feature.
Thanks,
