### ISSUE TITLE
[Next] Field type suggestion: flexible field

### ISSUE THREAD

**Issue by gryphonmyers** [COCOPi/cockpit#475]
The field would be one of some specified group of types.  Before entering data, the user selects a field type. 

Use case: suppose I have a field that I want to be enterable as Markdown, HTML or WYSIWYG, depending on user preference. With the 'flex' field type I can specify those three field types, then when the user gets to my field, they have a dropdown, tabs, whatever allowing them to switch between these types.

I would see this field as strictly being ONE of the types though and it should not retain data for any field type other than the current one (otherwise it would be too similar to the repeater field). For this reason I would suggest that changing a field's type spawns a confirmation prompt, warning of potential data loss.

**Comment by aheinze** [comment]
well, I can only see a use case for this switching between content editors, for other field types it just won't make sense. But then again, I also don't think that you want to switch between markdown and wysiwyg, because at the point where you consume the data you need to know if you need to parse it as markdown or just use it as it is. I understand your intention but I think there is no valid real life scenario for that and instead will only complicate things.

btw. you should be able to switch in the source mode in the wysiwyg editor.

**Comment by gryphonmyers** [comment]
There is another use case, but it is particular to collection links so
wouldn't necessarily justify an entirely new field type. Numerous times
when modeling my data I have needed a link of one type OR another. I've
been satisfying this need by making fields for both and only filling in one
or the other, but that isn't ideal because it would be possible for someone
who didn't understand the setup to enter both.

The need could also be satisfied with a "limit" parameter on the repeater
field. In my case, I'd be supplying a limit of 1 item and making either
collection link an available option. This does mean the data will be
wrapped in an unnecessary array, but that's not the end of the world.

**Comment by aheinze** [comment]
The limit option is a good idea 👍🏻

**Comment by gryphonmyers** [comment]
I'm content with the limit option for now, closing
